# Generated by Django 6.1.1 on 2026-10-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('harinas', 'Harinas y secos'), ('azucares', 'Azúcares y endulzantes'), ('lacteos', 'Lácteos y huevos'), ('chocolates', 'Chocolates y coberturas'), ('decoracion', 'Decoración'), ('utensilios', 'Utensilios y moldes'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
    ]
